name: Terraform CI

on:
  push:
    branches: [ trivy_scan ]

permissions:
  id-token: write
  contents: read

jobs:


  sandbox-0040-cleint-vpn:
    runs-on: ubuntu-latest

    concurrency:
      group: sandbox-0040-client-vpn
      cancel-in-progress: false

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Clean Root Certificate
        working-directory: terraform/infra/akm-solutions-sandbox/0040-client-vpn
        run: |
          CLEAN_CERT=$(tr -d '\000' < vpn_root_base64.txt | sed '1d;$d' | tr -d '\n\r')
          echo "::add-mask::$CLEAN_CERT"
          echo "TF_VAR_root_certificate_data=$CLEAN_CERT" >> $GITHUB_ENV
