name: Terraform CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

permissions:
  id-token: write
  contents: read

jobs:

  sandbox-0000-backend:
    runs-on: ubuntu-latest

    concurrency:
      group: sandbox-0000-backend
      cancel-in-progress: false

    steps:
      - name: Checkout
        uses: actions/checkout@v6

      - name: Azure Login
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3

      - name: Terraform Init
        working-directory: terraform/infra/akm-solutions-sandbox/0000-backend
        run: terraform init

      - name: Terraform Validate
        working-directory: terraform/infra/akm-solutions-sandbox/0000-backend
        run: terraform validate

      - name: Terraform Plan
        working-directory: terraform/infra/akm-solutions-sandbox/0000-backend
        run: terraform plan -out=tfplan

      - name: Terraform Apply
        if: github.event_name == 'push'
        working-directory: terraform/infra/akm-solutions-sandbox/0000-backend
        run: terraform apply -auto-approve tfplan


  sandbox-0030-networking:
    needs: sandbox-0000-backend
    runs-on: ubuntu-latest

    concurrency:
      group: sandbox-0030-networking
      cancel-in-progress: false

    steps:
      - name: Checkout
        uses: actions/checkout@v6

      - name: Azure Login
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3

      - name: Terraform Init
        working-directory: terraform/infra/akm-solutions-sandbox/0030-networking
        run: terraform init

      - name: Terraform Validate
        working-directory: terraform/infra/akm-solutions-sandbox/0030-networking
        run: terraform validate

      - name: Terraform Plan
        working-directory: terraform/infra/akm-solutions-sandbox/0030-networking
        run: terraform plan -out=tfplan

      - name: Terraform Apply
        if: github.event_name == 'push'
        working-directory: terraform/infra/akm-solutions-sandbox/0030-networking
        run: terraform apply -auto-approve tfplan

  sandbox-0040-cleint-vpn:
    needs: sandbox-0030-networking
    runs-on: ubuntu-latest

    concurrency:
      group: sandbox-0040-client-vpn
      cancel-in-progress: false

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Azure Login
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3

      - name: Terraform Init
        working-directory: terraform/infra/akm-solutions-sandbox/0040-client-vpn
        run: terraform init


      - name: Clean Root Certificate
        working-directory: terraform/infra/akm-solutions-sandbox/0040-client-vpn
        run: |
          CLEAN_CERT=$(sed '1d;$d' vpn_root_base64.txt | tr -d '\n\r')
          echo "::add-mask::$CLEAN_CERT"
          echo "TF_VAR_root_certificate_data=$CLEAN_CERT" >> $GITHUB_ENV

      - name: Terraform Validate
        working-directory: terraform/infra/akm-solutions-sandbox/0040-client-vpn
        run: terraform validate

      - name: Terraform Plan
        working-directory: terraform/infra/akm-solutions-sandbox/0040-client-vpn
        run: terraform plan -input=false -out=tfplan

      - name: Terraform Apply
        if: github.event_name == 'push'
        working-directory: terraform/infra/akm-solutions-sandbox/0040-client-vpn
        run: terraform apply -auto-approve tfplan