name: Trivy Scan

on:
  push:
    branches: [ main ]
  pull_request:

jobs:
  scan:
    runs-on: ubuntu-latest

    env:
      TRIVY_VERSION: v0.69.3
      PYTHON_VERSION: "3.13"

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Cache Trivy DB
        uses: actions/cache@v4
        with:
          path: .trivycache
          key: trivy-db-${{ runner.os }}
          restore-keys: |
            trivy-db-

      - name: Install Trivy
        run: |
          curl -sfL https://raw.githubusercontent.com/aquasecurity/trivy/main/contrib/install.sh | \
          sudo sh -s -- -b /usr/local/bin $TRIVY_VERSION

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ env.PYTHON_VERSION }}

      - name: Install dependencies
        run: |
          pip install --no-cache-dir pyyaml

      - name: Extract Images
        run: |
          python pre_process.py

      - name: Run Trivy Scan
        run: |
          chmod +x execute_trivy.sh
          ./execute_trivy.sh

      - name: Generate Final Report
        run: |
          python post_process.py

      - name: Upload report
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: trivy-report
          path: results/final_report.json

      - name: Print Summary
        if: always()
        run: |
          echo "==== FINAL REPORT ===="
          cat results/final_report.json || echo "No report generated"